### ISSUE TITLE
How can you show information for cleavage sites anchored on PASs?

### ISSUE THREAD

**Issue by rpghjs** [serenolopezdarwin/apanalysis#2]
Hi,
Actually, I  have made attempts  to  reproduce the panel "Position from annotated cleavage site(nt)" from Supplementary Figure 1 in the paper . I'm curious what kind of work bag do you use.
if possibie,I'm looking forward to the clue.

**Comment by vagarwal87** [comment]
I don't quite understand your question -- what do you mean by "work bag"? Did you look at the methods described in the legend and Methods section carefully to try to reproduce it? The main text legend for similar figure also describes how we created the plot.

**Comment by rpghjs** [comment]
Thanks for your reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Vikram ***@***.***&gt;; 
发送时间: 2021年9月11日(星期六) 凌晨5:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [serenolopezdarwin/apanalysis] How can you show information for cleavage sites anchored on PASs? (#2)





 
I don't quite understand your question -- what do you mean by "work bag"? Did you look at the methods described in the legend and Methods section carefully to try to reproduce it? The main text legend for similar figure also describes how we created the plot.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
