### ISSUE TITLE
The required input file “3pseq.bed”

### ISSUE THREAD

**Issue by XiangningDing-AU** [serenolopezdarwin/apanalysis#3]
The pipeline is really inspiring and useful! But I have a problem. How is the required input file “3pseq.bed” generated and also the “mouse_median_expr.txt”? Is “3pseq.bed”  the merged bed file of the 14 bed files from GSE52528?

**Comment by vagarwal87** [comment]
If you could find Sereno's Princeton address and send a joint email to him and me (vikram.agarwal {at} sanofi {dot} com), we could learn how 3pseq.bed is generated. As for mouse_median_expr.txt, this was generated by using a large matrix of gene expression values across many samples in the mouse, and then taking the median expression level across samples to get 1 value per gene. It can be found in Agarwal & Shendure Cell Reports 2020. If you need one or both files, we're happy to provide them to you after you email us.

**Comment by XiangningDing-AU** [comment]
Thanks very much in advance for your kind help!
